services:
  - type: web
    name: biblia-wyjasnienia
    env: python
    buildCommand: ""
    startCommand: python server.py
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: BIBLE_API_KEY
        sync: false
